print ("--------access granted-------- ")
import time
time.sleep(1)
print ("hacking in 20")
time.sleep(3)
print ("hacking completed ")
time.sleep(5)
print ("downloading device info in 10 sec ")
time.sleep(2)
print ("loading10%")
time.sleep(2)
print ("loading 20%")
time.sleep(1)
print ("loading 50%")
time.sleep(2)
print ("loading 83%")
time.sleep(1)
print ("loading 100%")
time.sleep(1)
print ("info downloaded ")
time.sleep(2)
print ("linking device ")
time.sleep(1)
print ("loading10%")
time.sleep(1)
print ("loading 20%")
time.sleep(1)
print ("loading 50%")
time.sleep(2)
print ("loading 83%")
time.sleep(3)
print ("loading 100%")
time.sleep(1)
print ("done")
time.sleep(5)
print ("downloading apps and account info ")
print ("loading10%")
time.sleep(1)
print ("loading 20%")
time.sleep(1)
print ("loading 50%")
time.sleep(2)
print ("loading 83%")
time.sleep(2)
print ("loading 100%")
print ("your device has been hacked ")
ttime.sleep(3)
print ("exit now ")
